# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Dr. Chen Zhang - 张晨
#title: Senior Network System Administrator
email: chenzhang22@suda.edu.cn
#website: https://chenzhang22.github.io/
Office: 303, Ligong Building, Tiancizhuang Campus
Address: No.333 Ganjiang East Road, Gusu District, Suzhou, China

# Dark Mode (true/false/never)
darkmode: false

# Social links
#twitter_username: facespics
github_username: chenzhang22
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: jameswgrant
#linkedin_username: jameswgrant
# xing_username: jekyll
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: 学院主页
  icon: fas fa-globe
  url: http://scst.suda.edu.cn/fd/61/c30505a523617/page.htm
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Chen Zhang and I'm currently a lecturer at School of Computer Science & Technology in Soochow University. I received my Ph.D. from Fudan University in 2022, supervised by Prof. <a href="https://cspengxin.github.io/">Xin Peng</a> and Prof. <a href="https://chenbihuan.github.io/">Bihuan Chen</a>. I received my M.Sc. from China University of Mining and Technology in 2016, supervised by Prof. <a href="https://siee.cumt.edu.cn/info/1012/1016.htm">Dunwei Gong</a>.
  My research focuses on intelligent software development, software evolution, software testing and continuous integration. 

content:
  - title: Publications # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: BuildFast History-Aware Build Outcome Prediction for Fast Feedback and Reduced Cost in Continuous Integration
        link: 

        quote: >
          BuildFast: History-Aware Build Outcome Prediction for Fast Feedback and Reduced Cost in Continuous Integration
        description: | # this will include new lines to allow paragraphs
          

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Fudan University
        caption: September 2017 - July 2022
        sub_title: Ph.D. Software Engineering
        quote: >
          
        description: | # this will include new lines to allow paragraphs
          Thesis: Build Failure and Performance Analysis for Continuous Integration.


      - layout: left
        title: China University of Mining and Technology
        caption: September 2013 - July 2016
        sub_title: M.Sc. Control Science and Engineering
        quote: >
          
        description: | # this will include new lines to allow paragraphs
          Thesis: Test Data Generation for Statement Coverage of Parallel Programs Based on Scheduling Sequence Selection and Genetic Algorithms.

      - layout: left
        title: China University of Mining and Technology
        caption: September 2009 - July 2013.06
        sub_title: B.Sc. Electrical Engineering and Automation
        quote: >

        description: | # this will include new lines to allow paragraphs


# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
